---
description: コンパイラ エラー CS1631
title: コンパイラ エラー CS1631
ms.date: 07/20/2015
f1_keywords:
- CS1631
helpviewer_keywords:
- CS1631
ms.assetid: bf0c5ff9-90a3-4db6-b4ee-0b93e31614e0
ms.openlocfilehash: d7495ad8ae25e15eb4ddc4798e5ed76debed8668
ms.sourcegitcommit: 5b475c1855b32cf78d2d1bbb4295e4c236f39464
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 09/24/2020
ms.locfileid: "91157630"
---
# <a name="compiler-error-cs1631"></a>コンパイラ エラー CS1631

catch 句の本体で値を生成することはできません。  
  
 yield ステートメントは、catch 句の本体内からは使用できません。 このエラーを回避するには、yield ステートメントを catch 句の本体の外に移動します。  
  
 次の例では CS1631 が生成されます。  
  
```csharp  
// CS1631.cs  
using System;  
using System.Collections;  
  
public class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()
   {  
      try  
      {  
      }  
      catch(Exception e)  
      {  
        yield return this;  // CS1631  
      }  
   }
  
   public static void Main()
   {  
   }  
}  
```
